---
title: "All-NBA team Analysis"
output: html_document
---

```{r, echo=FALSE, message=FALSE}
suppressPackageStartupMessages({
  # Data wrangling + plotting
library(tidyverse)
library(data.table)
library(caret)
library(RColorBrewer)
library(ggplot2)
library(ggrepel)
  
  # Multinomial regression
library(nnet)
  # Utilities
library(dplyr)
library(reshape2)
library(knitr)
library(kableExtra)
set.seed(400)
})
```


##DATA CLEANING/FORMATTING
```{r}

# Load 2018 Dataset
df_18 <- read_csv("all_nba_2018.csv",show_col_types = FALSE)

#Select Numeric Performance Stats (should be all of them)
df_numeric18 <- df_18 %>% select(minutes_pg,
  fga,
  fg3a,
  fta,
  pts_per_g,
  trb_per_g,
  ast_per_g,
  stl_per_g,
  blk_per_g,
  fg_pct,
  fg3_pct,
  ft_pct,
  games
)


# Load 2022 dataset
df <- read_csv("all_nba_2022.csv",show_col_types = FALSE)

#Select numeric variables
df_numeric <- df %>% select(minutes_pg,
  fga,
  fg3a,
  fta,
  pts_per_g,
  trb_per_g,
  ast_per_g,
  stl_per_g,
  blk_per_g,
  fg_pct,
  fg3_pct,
  ft_pct,
  games
)
# Update Plot Labels
var_labels <- c(
  minutes_pg = "Minutes per Game",
  fga        = "Field Goal Attempts",
  fg3a       = "3-Point Attempts",
  fta        = "Free Throw Attempts",
  pts_per_g  = "Points per Game",
  trb_per_g  = "Total Rebounds per Game",
  ast_per_g  = "Assists per Game",
  stl_per_g  = "Steals per Game",
  blk_per_g  = "Blocks per Game",
  fg_pct     = "Field Goal %", 
  fg3_pct    = "3-Point %", 
  ft_pct     = "Free Throw %", 
  games      = "Games Played"
)
```


## Some standard plots for visualization (2022 season)

```{r}
df <- read.csv("all_nba_2022.csv")

mean_stats <- df %>%
  select(-namePlayer, -all_nba_team) %>%
  summarise(across(everything(), \(x) mean(x, na.rm = TRUE))) %>%
  pivot_longer(cols = everything(),
               names_to = "stat",
               values_to = "mean_value")
mean_stats

mean_stats_plot <- ggplot(mean_stats, aes(x = reorder(stat, mean_value), y = mean_value)) +
  geom_col() +
  coord_flip() +
  labs(title = "Mean Values of Player Statistics",
       x = "Statistic",
       y = "Mean") +
  theme_minimal()
mean_stats_plot
saveRDS(mean_stats_plot, "mean_stats_plot.rds")




PTS3PA_18 <- ggplot(df_18, aes(x = fg3a, y = pts_per_g, se = FALSE)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Points vs 3PA (2018)",
       subtitle = "Correlation = 0.91",
       x = "3-Point Attempts per Game",
       y = "Points per Game") +
  theme_minimal()
PTS3PA_18
saveRDS(PTS3PA_18, "PTS3PA_18.rds")


PTS3PA_22 <- ggplot(df, aes(x = fg3a, y = pts_per_g)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Points vs 3PA (2022)",
       subtitle = "Correlation = 0.71",
       x = "3-Point Attempts per Game",
       y = "Points per Game") +
  theme_minimal()
PTS3PA_22
saveRDS(PTS3PA_22, "PTS3PA_22.rds")


tpa_fg_18 <- ggplot(df_18, aes(x = fg3_pct, y = fga)) +
  geom_point(color = "blue", size = 3) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "3-Point % vs Field Goal Attempts 2018",
       x = "3-Point %", y = "Field Goal Attempts per Game") +
  theme_minimal()
tpa_fg_18
saveRDS(tpa_fg_18, "tpa_fg18.rds")

fga_pts_18 <- ggplot(df_18, aes(x = fga, y = pts_per_g)) +
  geom_point(color = "darkgreen", size = 3) +
   geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Field Goal Attempts vs Points per Game 2018",
       x = "Field Goal Attempts per Game", y = "Points per Game") +
  theme_minimal()
fga_pts_18
saveRDS(fga_pts_18, "fga_pts18.rds")

tpa_fg <- ggplot(df, aes(x = fg3_pct, y = fga)) +
  geom_point(color = "blue", size = 3) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "3-Point % vs Field Goal Attempts 2022",
       x = "3-Point %", y = "Field Goal Attempts per Game") +
  theme_minimal()
tpa_fg
saveRDS(tpa_fg, "tpa_fg.rds")

fga_pts <- ggplot(df, aes(x = fga, y = pts_per_g)) +
  geom_point(color = "darkgreen", size = 3) +
   geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Field Goal Attempts vs Points per Game 2022",
       x = "Field Goal Attempts per Game", y = "Points per Game") +
  theme_minimal()
fga_pts
saveRDS(fga_pts, "fga_pts.rds")
```


## Creating Standard Correlations
```{r}

# Compute correlation matrix (2022) using pairwise
corr_mat <- cor(df_numeric, use = "pairwise.complete.obs")

# Convert to long format for ggplot heatmap
corr_df <- reshape2::melt(corr_mat)

# Repeat for 2018 season
corr_mat18 <- cor(df_numeric18, use = "pairwise.complete.obs")

corr_df18 <- reshape2::melt(corr_mat18)
```


#3 Plotting Correlations
```{r}
set.seed(400)

# Heatmap for 2022
corr22 <- ggplot(corr_df, aes(Var1, Var2, fill = value)) +
  geom_tile() +
  geom_text(aes(label = sprintf("%.2f", value)), size = 2) + 
  scale_fill_gradient2(low = "#d73027", mid = "#fee08b", high = "#1a9850",
                        midpoint = 0, limits = c(-1, 1)) +
  scale_x_discrete(labels = var_labels) +  
  scale_y_discrete(labels = var_labels) +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    axis.title = element_blank(),
    panel.grid = element_blank()
  ) +
  coord_fixed() +
  labs(title = "2022 NBA Heatmap")

saveRDS(corr22, "corr22.rds")

# Heatmap for 2018
corr18 <- ggplot(corr_df18, aes(Var1, Var2, fill = value)) +
  geom_tile() +
  geom_text(aes(label = sprintf("%.2f", value)), size = 2) +
  scale_fill_gradient2(low = "#d73027", mid = "#fee08b", high = "#1a9850",
                       midpoint = 0, limits = c(-1, 1)) +
  scale_x_discrete(labels = var_labels) +  
  scale_y_discrete(labels = var_labels) +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    axis.title = element_blank(),
    panel.grid = element_blank()
  ) +
  coord_fixed() + 
  labs(title = "2018 NBA Heatmap")


print(corr18)
print(corr22)

saveRDS(corr18, "corr18.rds")
```

```{r}

##Confusion and Correlation Matrices using Bootstrapping

set.seed(400)


#Reload dataset for modeling
df <- read.csv("all_nba_2022.csv")
df$all_nba_team <- as.factor(df$all_nba_team)


B <- 1000

conf_matrices <- list() #Store each bootstrap confusion matrix

for (i in 1:B) {
  
# Resampling rows with replacement until all classes appear, ie: Team 1,2 and 3
  repeat {
    bootstrap_indices <- sample(1:nrow(df), replace = TRUE)
    bootstrap_sample <- df[bootstrap_indices, ]
    
  
    if (all(levels(df$all_nba_team) %in% bootstrap_sample$all_nba_team)) break
  }
  
  
  #Fit multinomial logistic model to create confusion matrix of All-NBA team placement
  
  model <- multinom(all_nba_team ~ games + minutes_pg + fga + fg3a + fta + 
                      pts_per_g + trb_per_g + ast_per_g + stl_per_g + blk_per_g + 
                      fg_pct + fg3_pct + ft_pct, 
                    data = bootstrap_sample, trace = FALSE)
  # Predict on the full dataset
  
  preds <- predict(model, newdata = df)
  
  # Confusion matrix for this bootstrap run
  cm <- confusionMatrix(preds, df$all_nba_team)
  
  conf_matrices[[i]] <- cm$table
}

#Average the confusion matrices across all bootstrap samples 5
avg_cm <- Reduce("+", conf_matrices) / B


print(avg_cm)

saveRDS(avg_cm, "avg_cm.rds")
```


```{r}
## Correlation Bootstrapping

num_vars <- df %>% 
  select(games, minutes_pg, fga, fg3a, fta,
         pts_per_g, trb_per_g, ast_per_g, stl_per_g, blk_per_g,
         fg_pct, fg3_pct, ft_pct)

B <- 1000
corr_list <- vector("list", B)

for (i in 1:B) {

  #Sample rows with replacement (bootstrap)
  bootstrap_indices <- sample(1:nrow(num_vars), replace = TRUE)
  boot_sample <- num_vars[bootstrap_indices, ]

#Compute correlation matrix for this sample
  corr_list[[i]] <- cor(boot_sample, use = "pairwise.complete.obs")
}

#Average Correlation matricies across all bootstrap iterations
avg_corr <- Reduce("+", corr_list) / B
avg_corr

corr_melt <- reshape2::melt(avg_corr)


# Plot bootstrapped average correlation matrix
corr_boot <- ggplot(corr_melt, aes(Var1, Var2, fill = value)) +
  geom_tile(color = "white") +
  geom_text(aes(label = sprintf("%.2f", value)), size = 3) +
  scale_fill_gradient2(low = "#d73027", mid = "#fee08b", high = "#1a9850",
    midpoint = 0, limits = c(-1, 1)
  ) +
  scale_x_discrete(labels = var_labels) + 
  scale_y_discrete(labels = var_labels) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  ) +
  labs(title = "Bootstrapped Average Correlation Matrix", fill = "Corr")

corr_boot

saveRDS(corr_boot, "corr_boot.rds")
```

```{r}
library(tibble)

pace_2018  <- 97.3
pace_2022  <- 97.0

tov_2018   <- 13.3
tov_2022   <- 12.8

orb_2018   <- 22.4
orb_2022   <- 23.1

players_2018 <- 494
players_2022 <- 15

league_compare <- tibble(
  season = c(2018, 2022),
  pace = c(pace_2018, pace_2022),
  tov_pct = c(tov_2018, tov_2022),
  orb_pct = c(orb_2018, orb_2022),
  num_players = c(players_2018, players_2022)
)

league_compare


saveRDS(league_compare, "league_compare") 
```


```{r}
## Monte Carlo Simulation for All Player Stats

set.seed(400)
B <- 1000   


num_vars <- df %>% select(minutes_pg, fga, fg3a, fta,
pts_per_g, trb_per_g, ast_per_g,
stl_per_g, blk_per_g, fg_pct, fg3_pct, ft_pct)

# Compute means and SDs for each stat

stat_means <- sapply(num_vars, mean, na.rm = TRUE)
stat_sds   <- sapply(num_vars, sd, na.rm = TRUE)


# Initialize data frame to store Monte Carlo simulated means

mc_summary <- data.frame(iteration = 1:B)

for (stat in colnames(num_vars)) {
mc_summary[[paste0("mean_", stat)]] <- numeric(B)
}

# Monte Carlo iterations

for (i in 1:B) {
sim_data <- sapply(names(stat_means), function(stat) {
rnorm(n = nrow(df), mean = stat_means[stat], sd = stat_sds[stat])
})
sim_data <- as.data.frame(sim_data)

# Store average simulated stat for this iteration

for (stat in colnames(sim_data)) {
mc_summary[[paste0("mean_", stat)]][i] <- mean(sim_data[[stat]])
}
}

#Plot distributions for selected stats

library(reshape2)
mc_melt <- melt(mc_summary, id.vars = "iteration")

mc_avg <- ggplot(mc_melt, aes(x = value)) +
geom_histogram(bins = 30, fill = "#1a9850", color = "white") +
facet_wrap(~variable, scales = "free_x") +
labs(title = "Monte Carlo Distributions of Average Player Stats",
x = "Simulated Average Value", y = "Frequency")

mc_avg

saveRDS(mc_avg, "mc_avg.rds")
```
Leauge Level Averages for NBA stats from a bootstrapped sample of the top 15 players



## Bootstrap Predicted MVP Points with 95% CI
```{r}

df <- read_csv("all_nba_2022.csv")


df <- df %>%
  arrange(desc(pts_per_g)) %>%
  mutate(rank = row_number())


df <- df %>%
  mutate(points = case_when(
    rank == 1 ~ 10,
    rank == 2 ~ 7,
    rank == 3 ~ 5,
    rank == 4 ~ 3,
    rank == 5 ~ 1,
    TRUE ~ 0
  ))


core_model <- lm(points ~ pts_per_g + trb_per_g + ast_per_g, data = df)

# Predicted points
df <- df %>%
  mutate(predicted_points = predict(core_model, newdata = df)) %>%
  arrange(desc(predicted_points))


set.seed(400)
B <- 1000
n <- nrow(df)

pred_matrix <- matrix(NA, nrow = B, ncol = n)
colnames(pred_matrix) <- df$namePlayer

for (i in 1:B) {
  boot_indices <- sample(1:n, replace = TRUE)
  boot_sample <- df[boot_indices, ]
  
  boot_model <- lm(points ~ pts_per_g + trb_per_g + ast_per_g, data = boot_sample)
  
  pred_matrix[i, ] <- predict(boot_model, newdata = df)
}


pred_matrix <- pmax(pred_matrix, 0)


avg_pred <- colMeans(pred_matrix)
ci_lower <- apply(pred_matrix, 2, quantile, 0.025)
ci_upper <- apply(pred_matrix, 2, quantile, 0.975)

pred_summary <- tibble(
  player = df$namePlayer,
  avg_pred = avg_pred,
  ci_lower = ci_lower,
  ci_upper = ci_upper,
  actual_points = df$points
) %>%
  arrange(desc(avg_pred))

boot_predSummary <- pred_summary


boot_predSummary

saveRDS(boot_predSummary, "boot_predSummary.rds")


boot_predMVP <- ggplot(pred_summary, aes(x = actual_points, y = avg_pred, label = player)) +
  geom_point(color = "forestgreen", size = 3) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2, color = "grey50") +
  geom_text_repel(size = 3) +
  labs(
    title = "Bootstrap Predicted MVP Points (Top 15 Players)",
    x = "Assigned Points (from Rank)",
    y = "Predicted MVP Points"
  ) +
  theme_minimal()

saveRDS(boot_predMVP, "boot_predMVP.rds")
```