---
title: "datascrape"
output: html_document
---

```{r}
library(nbastatR)
library(dplyr)
```

```{r}
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)

all_nba_2022_players <- c(
  "Giannis Antetokounmpo",
  "Devin Booker",
  "Luka Dončić",
  "Nikola Jokić",
  "Jayson Tatum",
  "Stephen Curry",
  "DeMar DeRozan",
  "Kevin Durant",
  "Joel Embiid",
  "Ja Morant",
  "LeBron James",
  "Chris Paul",
  "Pascal Siakam",
  "Karl-Anthony Towns",
  "Trae Young"
)

all_nba_2022_team_map <- tibble::tibble(
  namePlayer = all_nba_2022_players,
  all_nba_team = c(
    # First Team
    "1",  # Giannis Antetokounmpo
    "1",  # Devin Booker
    "1",  # Luka Dončić
    "1",  # Nikola Jokić
    "1",  # Jayson Tatum
    # Second Team
    "2", # Stephen Curry
    "2", # DeMar DeRozan
    "2", # Kevin Durant
    "2", # Joel Embiid
    "2", # Ja Morant
    # Third Team
    "3",  # LeBron James
    "3",  # Chris Paul
    "3",  # Pascal Siakam
    "3",  # Karl-Anthony Towns
    "3"   # Trae Young
  )
)

logs_2022 <- game_logs(
  seasons = 2022,
  league = "NBA",
  result_types = "player",
  season_types = "Regular Season",
  nest_data = FALSE,
  assign_to_environment = FALSE,
  return_message = FALSE
)

all_nba_logs <- logs_2022 %>%
  filter(namePlayer %in% all_nba_2022_players)

all_nba_2022 <- all_nba_logs %>%
  group_by(namePlayer) %>%
  summarise(
    games       = n(),
    minutes_pg  = mean(minutes, na.rm = TRUE),
    fga         = mean(fga, na.rm = TRUE),
    fg3a        = mean(fg3a, na.rm = TRUE),
    fta         = mean(fta, na.rm = TRUE),
    pts_per_g   = mean(pts, na.rm = TRUE),
    trb_per_g   = mean(treb, na.rm = TRUE),
    ast_per_g   = mean(ast, na.rm = TRUE),
    stl_per_g   = mean(stl, na.rm = TRUE),
    blk_per_g   = mean(blk, na.rm = TRUE),
    fg_pct      = mean(pctFG,  na.rm = TRUE),
    fg3_pct     = mean(pctFG3, na.rm = TRUE),
    ft_pct      = mean(pctFT,  na.rm = TRUE),
  ) %>%
  left_join(all_nba_2022_team_map, by = "namePlayer") %>%
  arrange(all_nba_team, desc(pts_per_g))

all_nba_2022

write.csv(all_nba_2022, "all_nba_2022.csv", row.names = FALSE)

```


```{r}
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)

all_nba_2018_players <- c(
  "Giannis Antetokounmpo",
  "Kemba Walker",
  "Paul George",
  "Nikola Jokić",
  "Damian Lillard",
  "Stephen Curry",
  "Kyrie Irving",
  "Kevin Durant",
  "Joel Embiid",
  "Kawhi Leonard",
  "LeBron James",
  "Russell Westbrook",
  "Blake Griffin",
  "Rudy Gobert",
  "James Harden"
)

all_nba_2018_team_map <- tibble::tibble(
  namePlayer = all_nba_2018_players,
  all_nba_team = c(
    # First Team
    "1",  # Giannis Antetokounmpo
    "3",  # Kemba Walker
    "1",  # Paul George
    "1",  # Nikola Jokić
    "2", # Damian Lillard
    "1",  # Stephen Curry
    "2", # Kyrie Irving
    "2", # Kevin Durant
    "2", # Joel Embiid
    "2", # Kawhi Leonard
    "3",  # LeBron James
    "3",  # Russell Westbrook
    "3",  # Blake Griffin
    "3",  # Rudy Gobert
    "1"   # James Harden
  )
)

logs_2018 <- game_logs(
  seasons = 2018,
  league = "NBA",
  result_types = "player",
  season_types = "Regular Season",
  nest_data = FALSE,
  assign_to_environment = FALSE,
  return_message = FALSE
)

all_nba_logs <- logs_2018 %>%
  filter(namePlayer %in% all_nba_2018_players)

all_nba_2018 <- all_nba_logs %>%
  group_by(namePlayer) %>%
  summarise(
    games       = n(),
    minutes_pg  = mean(minutes, na.rm = TRUE),
    fga         = mean(fga, na.rm = TRUE),
    fg3a        = mean(fg3a, na.rm = TRUE),
    fta         = mean(fta, na.rm = TRUE),
    pts_per_g   = mean(pts, na.rm = TRUE),
    trb_per_g   = mean(treb, na.rm = TRUE),
    ast_per_g   = mean(ast, na.rm = TRUE),
    stl_per_g   = mean(stl, na.rm = TRUE),
    blk_per_g   = mean(blk, na.rm = TRUE),
    fg_pct      = mean(pctFG,  na.rm = TRUE),
    fg3_pct     = mean(pctFG3, na.rm = TRUE),
    ft_pct      = mean(pctFT,  na.rm = TRUE),
  ) %>%
  left_join(all_nba_2018_team_map, by = "namePlayer") %>%
  arrange(all_nba_team, desc(pts_per_g))

all_nba_2018

write.csv(all_nba_2018, "all_nba_2018.csv", row.names = FALSE)


```



